/// this code is almost entirely generated by Claude Code and thus of dubious
/// copyright status
///
use crate::db::items::Item;
use crate::filter::RuleType;
use regex::{Regex, RegexBuilder, escape};
use rust_stemmers::{Algorithm, Stemmer};
use unicode_normalization::UnicodeNormalization;

fn strip_diacritics(s: &str) -> String {
    s.nfd()
        .filter(|c| !unicode_normalization::char::is_combining_mark(*c))
        .collect()
}

/// Build a stripped (no-diacritics) version of original, plus a mapping
/// from each byte offset in the stripped string to the corresponding
/// byte offset in the original.
fn strip_diacritics_with_offsets(original: &str) -> (String, Vec<usize>) {
    let mut stripped = String::new();
    // Map: for each byte in stripped, the corresponding byte offset in original
    let mut map: Vec<usize> = Vec::new();
    let mut orig_offset = 0;
    for ch in original.chars() {
        let ch_len = ch.len_utf8();
        // Decompose this character
        let mut base_found = false;
        for decomposed in ch.to_string().nfd() {
            if unicode_normalization::char::is_combining_mark(decomposed) {
                continue;
            }
            let before = stripped.len();
            stripped.push(decomposed);
            // Each new byte in stripped maps to orig_offset
            for _ in before..stripped.len() {
                map.push(orig_offset);
            }
            base_found = true;
        }
        let _ = base_found;
        orig_offset += ch_len;
    }
    map.push(original.len()); // sentinel for end-of-string
    (stripped, map)
}

/// Split HTML content into text segments and tag segments, apply regex
/// highlighting only to text segments, and reassemble.
fn highlight_preserving_tags(html: &str, re: &Regex, wrap: &dyn Fn(&str) -> String) -> String {
    let mut result = String::new();
    let mut pos = 0;
    let bytes = html.as_bytes();
    while pos < bytes.len() {
        if bytes[pos] == b'<' {
            // Copy the entire tag as-is
            let start = pos;
            while pos < bytes.len() && bytes[pos] != b'>' {
                pos += 1;
            }
            if pos < bytes.len() {
                pos += 1; // skip '>'
            }
            result.push_str(&html[start..pos]);
        } else {
            // Collect text until next tag
            let start = pos;
            while pos < bytes.len() && bytes[pos] != b'<' {
                pos += 1;
            }
            let text = &html[start..pos];
            result.push_str(&re.replace_all(text, |caps: &regex::Captures| wrap(&caps[0])));
        }
    }
    result
}

/// Like highlight_preserving_tags but with diacritics-insensitive matching.
fn highlight_diacritics_preserving_tags(
    html: &str,
    re: &Regex,
    wrap: &dyn Fn(&str) -> String,
) -> String {
    let mut result = String::new();
    let mut pos = 0;
    let bytes = html.as_bytes();
    while pos < bytes.len() {
        if bytes[pos] == b'<' {
            let start = pos;
            while pos < bytes.len() && bytes[pos] != b'>' {
                pos += 1;
            }
            if pos < bytes.len() {
                pos += 1;
            }
            result.push_str(&html[start..pos]);
        } else {
            let start = pos;
            while pos < bytes.len() && bytes[pos] != b'<' {
                pos += 1;
            }
            let text = &html[start..pos];
            let (normalized, offset_map) = strip_diacritics_with_offsets(text);
            let mut last = 0;
            for m in re.find_iter(&normalized) {
                let orig_start = offset_map[m.start()];
                let orig_end = offset_map[m.end()];
                result.push_str(&text[last..orig_start]);
                result.push_str(&wrap(&text[orig_start..orig_end]));
                last = orig_end;
            }
            result.push_str(&text[last..]);
        }
    }
    result
}

impl Item {
    pub fn title_highlighted(&self) -> String {
        let title = ammonia::Builder::new()
            .tags(std::collections::HashSet::new())
            .clean(&self.title)
            .to_string();
        let wrap = |s: &str| format!("<span class=\"filter-highlight\">{}</span>", s);

        match &self.rule {
            None => title,
            Some(r) => match r.rule_type {
                RuleType::TitleAll | RuleType::UnionAll => {
                    // Split text into words, wrap each word that appears in rule text
                    let rule_words: Vec<String> = r
                        .text
                        .split_whitespace()
                        .map(|w| w.to_lowercase())
                        .collect();
                    // Split title preserving whitespace, wrap matching words
                    let mut result = String::new();
                    let mut chars = title.chars().peekable();
                    while chars.peek().is_some() {
                        if chars.peek().unwrap().is_whitespace() {
                            while chars.peek().is_some_and(|c| c.is_whitespace()) {
                                result.push(chars.next().unwrap());
                            }
                        } else {
                            let mut word = String::new();
                            while chars.peek().is_some_and(|c| !c.is_whitespace()) {
                                word.push(chars.next().unwrap());
                            }
                            let stripped: String =
                                word.chars().filter(|c| c.is_alphanumeric()).collect();
                            if rule_words.contains(&stripped.to_lowercase()) {
                                result.push_str(&wrap(&word));
                            } else {
                                result.push_str(&word);
                            }
                        }
                    }
                    result
                }
                RuleType::TitleExactWord | RuleType::UnionExactWord => {
                    // Exact word match, case-sensitive, ignoring surrounding punctuation
                    let mut result = String::new();
                    let mut chars = title.chars().peekable();
                    while chars.peek().is_some() {
                        if chars.peek().unwrap().is_whitespace() {
                            while chars.peek().is_some_and(|c| c.is_whitespace()) {
                                result.push(chars.next().unwrap());
                            }
                        } else {
                            let mut word = String::new();
                            while chars.peek().is_some_and(|c| !c.is_whitespace()) {
                                word.push(chars.next().unwrap());
                            }
                            let stripped: String =
                                word.chars().filter(|c| c.is_alphanumeric()).collect();
                            if stripped == r.text {
                                result.push_str(&wrap(&word));
                            } else {
                                result.push_str(&word);
                            }
                        }
                    }
                    result
                }
                RuleType::TitlePhrase | RuleType::UnionPhrase => {
                    // Case-sensitive substring match
                    let re = Regex::new(&escape(&r.text)).unwrap();
                    re.replace_all(&title, |caps: &regex::Captures| wrap(&caps[0]))
                        .into_owned()
                }
                RuleType::TitlePhraseLowerCase | RuleType::UnionPhraseLowerCase => {
                    // Case-insensitive, diacritics-insensitive match
                    let (normalized_title, offset_map) = strip_diacritics_with_offsets(&title);
                    let normalized_text = strip_diacritics(&r.text);
                    let re = RegexBuilder::new(&escape(&normalized_text))
                        .case_insensitive(true)
                        .build()
                        .unwrap();
                    let mut result = String::new();
                    let mut last = 0;
                    for m in re.find_iter(&normalized_title) {
                        let orig_start = offset_map[m.start()];
                        let orig_end = offset_map[m.end()];
                        result.push_str(&title[last..orig_start]);
                        result.push_str(&wrap(&title[orig_start..orig_end]));
                        last = orig_end;
                    }
                    result.push_str(&title[last..]);
                    result
                }
                RuleType::TitleWord | RuleType::UnionWord => {
                    // Stem-based match: wrap any word whose stem matches the rule text's stem
                    let en_stemmer = Stemmer::create(Algorithm::English);
                    let target_stem = en_stemmer.stem(&r.text.to_lowercase()).into_owned();
                    let mut result = String::new();
                    let mut chars = title.chars().peekable();
                    while chars.peek().is_some() {
                        if chars.peek().unwrap().is_whitespace() {
                            while chars.peek().is_some_and(|c| c.is_whitespace()) {
                                result.push(chars.next().unwrap());
                            }
                        } else {
                            let mut word = String::new();
                            while chars.peek().is_some_and(|c| !c.is_whitespace()) {
                                word.push(chars.next().unwrap());
                            }
                            let stripped: String =
                                word.chars().filter(|c| c.is_alphanumeric()).collect();
                            let stem = en_stemmer.stem(&stripped.to_lowercase()).into_owned();
                            if stem == target_stem {
                                result.push_str(&wrap(&word));
                            } else {
                                result.push_str(&word);
                            }
                        }
                    }
                    result
                }
                _ => title,
            },
        }
    }

    pub fn content_highlighted(&self) -> String {
        let content = ammonia::clean(&self.content);
        let wrap = |s: &str| format!("<span class=\"filter-highlight\">{}</span>", s);

        match &self.rule {
            None => content,
            Some(r) => match r.rule_type {
                RuleType::UnionAll => {
                    // Split text into words, wrap each word that appears in rule text
                    let rule_words: Vec<String> = r
                        .text
                        .split_whitespace()
                        .map(|w| w.to_lowercase())
                        .collect();
                    let mut result = String::new();
                    let mut chars = content.chars().peekable();
                    while chars.peek().is_some() {
                        if chars.peek().unwrap().is_whitespace() {
                            while chars.peek().is_some_and(|c| c.is_whitespace()) {
                                result.push(chars.next().unwrap());
                            }
                        } else if chars.peek().unwrap() == &'<' {
                            // Preserve HTML tags from ammonia::clean
                            while chars.peek().is_some_and(|c| *c != '>') {
                                result.push(chars.next().unwrap());
                            }
                            if chars.peek().is_some() {
                                result.push(chars.next().unwrap()); // '>'
                            }
                        } else {
                            let mut word = String::new();
                            while chars
                                .peek()
                                .is_some_and(|c| !c.is_whitespace() && *c != '<')
                            {
                                word.push(chars.next().unwrap());
                            }
                            let stripped: String =
                                word.chars().filter(|c| c.is_alphanumeric()).collect();
                            if rule_words.contains(&stripped.to_lowercase()) {
                                result.push_str(&wrap(&word));
                            } else {
                                result.push_str(&word);
                            }
                        }
                    }
                    result
                }
                RuleType::UnionExactWord => {
                    // Exact word match, case-sensitive, ignoring surrounding punctuation
                    let mut result = String::new();
                    let mut chars = content.chars().peekable();
                    while chars.peek().is_some() {
                        if chars.peek().unwrap().is_whitespace() {
                            while chars.peek().is_some_and(|c| c.is_whitespace()) {
                                result.push(chars.next().unwrap());
                            }
                        } else if chars.peek().unwrap() == &'<' {
                            while chars.peek().is_some_and(|c| *c != '>') {
                                result.push(chars.next().unwrap());
                            }
                            if chars.peek().is_some() {
                                result.push(chars.next().unwrap());
                            }
                        } else {
                            let mut word = String::new();
                            while chars
                                .peek()
                                .is_some_and(|c| !c.is_whitespace() && *c != '<')
                            {
                                word.push(chars.next().unwrap());
                            }
                            let stripped: String =
                                word.chars().filter(|c| c.is_alphanumeric()).collect();
                            if stripped == r.text {
                                result.push_str(&wrap(&word));
                            } else {
                                result.push_str(&word);
                            }
                        }
                    }
                    result
                }
                RuleType::ContentPhrase | RuleType::UnionPhrase => {
                    // Case-sensitive substring match, skip inside HTML tags
                    let re = Regex::new(&escape(&r.text)).unwrap();
                    highlight_preserving_tags(&content, &re, &wrap)
                }
                RuleType::ContentPhraseLowerCase | RuleType::UnionPhraseLowerCase => {
                    // Case-insensitive, diacritics-insensitive match
                    let normalized_text = strip_diacritics(&r.text);
                    let re = RegexBuilder::new(&escape(&normalized_text))
                        .case_insensitive(true)
                        .build()
                        .unwrap();
                    // Work on text-only portions, preserving tags
                    highlight_diacritics_preserving_tags(&content, &re, &wrap)
                }
                RuleType::UnionWord => {
                    // Stem-based match
                    let en_stemmer = Stemmer::create(Algorithm::English);
                    let target_stem = en_stemmer.stem(&r.text.to_lowercase()).into_owned();
                    let mut result = String::new();
                    let mut chars = content.chars().peekable();
                    while chars.peek().is_some() {
                        if chars.peek().unwrap().is_whitespace() {
                            while chars.peek().is_some_and(|c| c.is_whitespace()) {
                                result.push(chars.next().unwrap());
                            }
                        } else if chars.peek().unwrap() == &'<' {
                            while chars.peek().is_some_and(|c| *c != '>') {
                                result.push(chars.next().unwrap());
                            }
                            if chars.peek().is_some() {
                                result.push(chars.next().unwrap());
                            }
                        } else {
                            let mut word = String::new();
                            while chars
                                .peek()
                                .is_some_and(|c| !c.is_whitespace() && *c != '<')
                            {
                                word.push(chars.next().unwrap());
                            }
                            let stripped: String =
                                word.chars().filter(|c| c.is_alphanumeric()).collect();
                            let stem = en_stemmer.stem(&stripped.to_lowercase()).into_owned();
                            if stem == target_stem {
                                result.push_str(&wrap(&word));
                            } else {
                                result.push_str(&word);
                            }
                        }
                    }
                    result
                }
                _ => content,
            },
        }
    }
}
